is_debug: true
dir:
    log: ./logs
    data: ./data
    cache: ./cache
    template: ./templates
db:
    host: localhost
    port: 3306
    user: customize_api
    password: customize-api
    dbname: customize_api
memcached:
    host: localhost
    port: 11211
    namespace: customize-api
